language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install -r requirements_ci.txt
  - pip install
  - python setup.py -q install
# command to run tests
script: pytest