os:
  - linux
  - windows

jobs:
  include:
    - os: linux
      python: 2.7
      script:
        - pip install tox-travis
        - tox -vv
    - os: linux
      python: 3.7
      script:
        - pip install tox-travis
        - tox -vv
    - os: windows
      script:
        - setup\setup\install-python-37.bat
        - setup\setup\install-python-37-deps.bat
        - wrappers\python27.bat -m pytest -h
        - wrappers\python37.bat -m pytest -h
        - wrappers\python37.bat -m black -h
