echo running regular tests...
coverage run --source=kttk,ktrack_api,kttk_widgets venv/Scripts/pytest-script.py --junitxml=junit_xml_tests.xml -o junit_suite_name=tests
coverage xml -o coverage_tests.xml