project: 
    folders:
        "{project_root}/{project_name}":
            - Assets
            - Shots
asset: 
    folders:
        "{project_root}/{project_name}/Assets/{asset_type}/{code}":
            - "{code}_Alembic"
            - "{code}_Textures"
            - "{code}_Input_2D"
            - "{code}_Input_3D"
            - "{code}_Maya":
                - __file__ :
                             name: workspace.mel
                             content: '''
                                      workspace -ot "scene" "{maya_scenes_location}";
                                      workspace -ot "mayaAscii" "{maya_scenes_location}";
                                      workspace -ot "mayaBinary" "{maya_scenes_location}";
                                      workspace -rt "images" "{asset_renderoutput_3D}";
                                      workspace -fr "alembicCache" "{asset_alembic}";
                                      workspace -fr "movie" "asset_playblast_location";
                                      '''
            - "{code}_out":
                - playblast
