project: 
    folders:
        "{project_root}/{project_name}":
            - Assets
            - Shots
asset: 
    folders:
        "{project_root}/{project_name}/Assets/{asset_type}/{code}":
            - "{code}_Alembic"
            - "{code}_Textures"
            - "{code}_Input_2D"
            - "{code}_Input_3D"
            - "{code}_Maya":
                - __file__ :
                             name: workspace.mel
                             content: '''
                                      workspace -fr "image" "{asset_renderoutput_3D}"; linebreak workspace -fr "alembicCache" "{asset_alembic}";
                                      '''
            - "{code}_out":
                - playblast
