project_root : "M:/Projekte/{year}"
project_folder: "{project_root}/{project_name}"

asset_folder: "{project_root}/{project_name}/{asset_type}/{code}"
asset_alembic: "{project_root}/{project_name}/Assets/{asset_type}/{code}/{code}_Alembic"
asset_renderoutput_3D: "{project_root}/{project_name}/Assets/{asset_type}/{code}/{code}_Input_3D"
asset_maya_workspace_location: "{project_root}/{project_name}/Assets/{asset_type}/{code}/{code}_Maya"
asset_maya_scenes_location: "{project_root}/{project_name}/Assets/{asset_type}/{code}/{code}_Maya"
asset_playblast_location: "{project_root}/{project_name}/Assets/{asset_type}/{code}/{code}_out/playblast"
render_image_file_name: "<Layer>/{version}/<Scene>"