name: Python CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        - setup\setup\install-python-27.bat
        - setup\setup\install-python-27-deps.bat
        - wrappers\python27.bat -m pytest -h
